[{"name": "test.test_red_green_blue.RedGreenBlue.test_called", "status": "errored", "message": "list index out of range", "passed": false, "points": ["p02-03.1"], "backtrace": ["  File \"C:\\Users\\haste\\anaconda3\\lib\\unittest\\case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"C:\\Users\\haste\\anaconda3\\lib\\unittest\\case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Users\\haste\\anaconda3\\lib\\unittest\\case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\haste\\OneDrive\\Desktop\\data-analysis-course\\dawp2020\\hy-data-analysis-with-python-2020\\part02-e03_red_green_blue\\test\\test_red_green_blue.py\", line 60, in test_called\n    result=red_green_blue()\n", "  File \"C:\\Users\\haste\\OneDrive\\Desktop\\data-analysis-course\\dawp2020\\hy-data-analysis-with-python-2020\\part02-e03_red_green_blue\\src\\red_green_blue.py\", line 11, in red_green_blue\n    lst.append('\\t'.join(a[0]))\n"]}, {"name": "test.test_red_green_blue.RedGreenBlue.test_content", "status": "errored", "message": "list index out of range", "passed": false, "points": ["p02-03.1"], "backtrace": ["  File \"C:\\Users\\haste\\anaconda3\\lib\\unittest\\case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"C:\\Users\\haste\\anaconda3\\lib\\unittest\\case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Users\\haste\\anaconda3\\lib\\unittest\\case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\haste\\OneDrive\\Desktop\\data-analysis-course\\dawp2020\\hy-data-analysis-with-python-2020\\part02-e03_red_green_blue\\test\\test_red_green_blue.py\", line 27, in test_content\n    result=red_green_blue()\n", "  File \"C:\\Users\\haste\\OneDrive\\Desktop\\data-analysis-course\\dawp2020\\hy-data-analysis-with-python-2020\\part02-e03_red_green_blue\\src\\red_green_blue.py\", line 11, in red_green_blue\n    lst.append('\\t'.join(a[0]))\n"]}, {"name": "test.test_red_green_blue.RedGreenBlue.test_size", "status": "errored", "message": "list index out of range", "passed": false, "points": ["p02-03.1"], "backtrace": ["  File \"C:\\Users\\haste\\anaconda3\\lib\\unittest\\case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"C:\\Users\\haste\\anaconda3\\lib\\unittest\\case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Users\\haste\\anaconda3\\lib\\unittest\\case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\haste\\OneDrive\\Desktop\\data-analysis-course\\dawp2020\\hy-data-analysis-with-python-2020\\part02-e03_red_green_blue\\test\\test_red_green_blue.py\", line 19, in test_size\n    result=red_green_blue()\n", "  File \"C:\\Users\\haste\\OneDrive\\Desktop\\data-analysis-course\\dawp2020\\hy-data-analysis-with-python-2020\\part02-e03_red_green_blue\\src\\red_green_blue.py\", line 11, in red_green_blue\n    lst.append('\\t'.join(a[0]))\n"]}]